version: '3'

services:
  waytogo-db:
    container_name: waytogo-db
    image: janek1010/waytogo-db:latest
    restart: always
    environment:
      POSTGRES_DB: "waytogo_db"
      POSTGRES_USER: "waytogo_user"
      POSTGRES_PASSWORD: "waytogo_password"
    ports:
      - "5432:5432"
    volumes:
      - db-waytogo:/var/lib/postgresql/data
    networks:
      - mynetwork

  waytogo:
    image: janek1010/waytogo:latest
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: "postgres"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://waytogo-db:5432/waytogo_db"
      SPRING_DATASOURCE_USERNAME: "waytogo_user"
      SPRING_DATASOURCE_PASSWORD: "waytogo_password"
      CORS_ALLOWED_ORIGINS: "http://localhost:4200,http://waytogo-frontend:80,http://localhost"
    ports:
      - "8090:8090"
    depends_on:
      - waytogo-db
    networks:
      - mynetwork

  waytogo-frontend:
    container_name: frontend
    image: janek1010/angular-waytogo
    restart: always
    ports:
      - "80:80"
    environment:
      API_URL: http://waytogo:8090/api
    depends_on:
      - waytogo
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  db-waytogo:
