version: '3'

# okej laczy sie teraz ale nie wiem czasem czy nie z lokalnym postgresem xdd ogarnac to i potem next bledy
services:
  waytogo-db:
    container_name: waytogo-db
    build:
      context: .
      dockerfile: Dockerfile-db
    #restart: always
    environment:
      POSTGRES_DB: "waytogo_db"
      POSTGRES_USER: "waytogo_user"
      POSTGRES_PASSWORD: "waytogo_password"
    ports:
      - "5432:5432" # zmień port z 5432 na 5433
    volumes:
      - ./db:/docker-entrypoint-initdb.d/

  waytogo:
    build: .
    #restart: always
    environment:
      SPRING_PROFILES_ACTIVE: "postgres"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://waytogo-db:5432/waytogo_db"
      SPRING_DATASOURCE_USERNAME: "waytogo_user"
      SPRING_DATASOURCE_PASSWORD: "waytogo_password"
    ports:
      - "8090:8090"
    depends_on:
      - waytogo-db
