version: '3'

services:
  waytogo-db:
    container_name: waytogo-db
    image: janek1010/waytogo-db:latest
    restart: always
    environment:
      POSTGRES_DB: "waytogo_db"
      POSTGRES_USER: "waytogo_user"
      POSTGRES_PASSWORD: "waytogo_password"
    ports:
      - "18121:5432"
    volumes:
      - db-waytogo:/var/lib/postgresql/data
    networks:
      - mynetwork

  waytogo:
    image: janek1010/waytogo:latest
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: "postgres"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://waytogo-db:5432/waytogo_db"
      SPRING_DATASOURCE_USERNAME: "waytogo_user"
      SPRING_DATASOURCE_PASSWORD: "waytogo_password"
      APP_CORS_ALLOWED_ORIGINS: "https://way2go.popi.pl/,http://localhost:4200,http://waytogo-frontend:80,http://localhost,https://way2go-api.popi.pl/,http://wa
y2go-api.popi.pl/,https://way2go.popi.pl/,http://way2go.popi.pl/,way2go.popi.pl"
    ports:
      - "18120:8090"
    depends_on:
      - waytogo-db
    networks:
      - mynetwork

  waytogo-frontend:
    container_name: frontend
    image: janek1010/angular-waytogo:latest
    restart: always
    ports:
      - "18122:80"
    environment:
      API_URL: http://way2go-api.popi.pl/api
      SERVER_NAME: way2go-api.popi.pl
    depends_on:
      - waytogo
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  db-waytogo:
